/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Arya Kamandanu
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        hasil = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        inputberatbadan = new javax.swing.JTextField();
        ideal = new javax.swing.JTextField();
        buttonperempuan = new javax.swing.JRadioButton();
        buttonlaki = new javax.swing.JRadioButton();
        keluar = new javax.swing.JButton();
        hitung = new javax.swing.JButton();
        cobalagi = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        inputtinggi = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        inputnama = new javax.swing.JTextField();
        diagnosa2 = new javax.swing.JTextField();
        diagnosa1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Cek Ideal tubuh");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, -1, -1));

        hasil.setText("Hasil diagnosa kesehatan");
        getContentPane().add(hasil, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, -1, 10));

        jLabel3.setText("kg");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, -1, -1));

        jLabel4.setText("Berat Badan");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, -1, -1));
        getContentPane().add(inputberatbadan, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 80, -1));

        ideal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idealActionPerformed(evt);
            }
        });
        getContentPane().add(ideal, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, 40, -1));

        buttonGroup1.add(buttonperempuan);
        buttonperempuan.setText("Perempuan");
        getContentPane().add(buttonperempuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, -1, -1));

        buttonGroup1.add(buttonlaki);
        buttonlaki.setText("Laki-Laki");
        getContentPane().add(buttonlaki, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, -1, -1));

        keluar.setText("Keluar");
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });
        getContentPane().add(keluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, -1, -1));

        hitung.setText("Hitung");
        hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitungActionPerformed(evt);
            }
        });
        getContentPane().add(hitung, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, -1, -1));

        cobalagi.setText("Coba Lagi");
        cobalagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cobalagiActionPerformed(evt);
            }
        });
        getContentPane().add(cobalagi, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, -1, -1));

        jLabel5.setText("Tinggi");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, -1, -1));

        jLabel6.setText("cm");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, -1, -1));

        jLabel7.setText("Jenis Kelamin");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, -1, -1));
        getContentPane().add(inputtinggi, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 80, -1));

        jLabel8.setText("kg");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, 30, 20));

        jLabel9.setText("Berat badan ideal anda adalah");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, -1, 10));

        jLabel10.setText("Nama");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, -1, -1));
        getContentPane().add(inputnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 170, -1));
        getContentPane().add(diagnosa2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, 310, -1));
        getContentPane().add(diagnosa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, 310, -1));

        setBounds(0, 0, 510, 498);
    }// </editor-fold>//GEN-END:initComponents

    private void idealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idealActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idealActionPerformed

    private void hitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitungActionPerformed
        String name =inputnama.getText();
        String gender;
       
        int berat = Integer.parseInt(inputberatbadan.getText());
        int tinggi = Integer.parseInt(inputtinggi.getText());
       
        if(buttonlaki.isSelected()){
            gender = buttonlaki.getText();
            int beratideal;
            beratideal=tinggi-100;
            ideal.setText(String.valueOf(beratideal));
          
        }
        else if(buttonperempuan.isSelected()){
            gender = buttonperempuan.getText();
            int beratideal;
            beratideal=tinggi-104;
            ideal.setText(String.valueOf(beratideal));
            
         }
         
        
      
        if(inputnama.getText().equals("") || inputberatbadan.getText().equals("") || 
           inputtinggi.getText().equals("")){
            hasil.setText("Isikan input");
            
        }
        
        
        
        
    }//GEN-LAST:event_hitungActionPerformed

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_keluarActionPerformed

    private void cobalagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cobalagiActionPerformed
inputberatbadan.setText("");
inputnama.setText("");
inputtinggi.setText("");
ideal.setText("");// TODO add your handling code here:
    }//GEN-LAST:event_cobalagiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JRadioButton buttonlaki;
    private javax.swing.JRadioButton buttonperempuan;
    private javax.swing.JButton cobalagi;
    private javax.swing.JTextField diagnosa1;
    private javax.swing.JTextField diagnosa2;
    private javax.swing.JLabel hasil;
    private javax.swing.JButton hitung;
    private javax.swing.JTextField ideal;
    private javax.swing.JTextField inputberatbadan;
    private javax.swing.JTextField inputnama;
    private javax.swing.JTextField inputtinggi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton keluar;
    // End of variables declaration//GEN-END:variables
}
